### ISSUE TITLE
model: support ChatGLM3 by zhipuai.cn in chat engine

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#182]

**Comment by shionphan** [comment]
but cant found opition in "Setup default LLM"

**Comment by Icemap** [comment]
> but cant found opition in "Setup default LLM"

Hi @shionphan. I think the feature that sets the LLMs or Chat Engine is an admin-only feature. I configured `GLM-4` of Zhipu AI before.
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/10b58e5d-7460-45e0-b1ab-0d785ecf7fb7">

**Comment by Icemap** [comment]
Let me close this issue due to the inactive activity. Feel free to reopen it if you have any questions or concerns.
