### ISSUE TITLE
Support different models 

### ISSUE THREAD

**Issue by Mini256** [pingcap/tidb.ai#196]
### LLM Models / Services

- [x] ChatGLM3 #182
- [x] Bedrock #181
- [x] Ollama #157
- [ ] xinference

### Embedding Models / Services

- [x] JinaAI Embedding

### Reranker Models / Services

- [x] JinaAI Reranker
- [x]  Cohere Reranker

**Comment by sykp241095** [comment]
Within all the models listed above but not already done, Bedrock is in the first priority, because we will announce the integrations between Bedrock and TiDB Vector in our HTAP Summit conference, which will be hosted on 9.22.

@Mini256
