### ISSUE TITLE
Your app is not fully configured yet. Please complete the setup process.

### ISSUE THREAD

**Issue by rickywu** [pingcap/tidb.ai#203]
I don't have account and can't login now

![image](https://github.com/user-attachments/assets/669818df-e33a-4b86-b264-6fbf92579857)

**Comment by rickywu** [comment]
the setup steps not mentioned admin@example.com default password

**Comment by 634750802** [comment]
Documented in https://github.com/pingcap/tidb.ai/commit/2f5b2b6e08d2f5f960eb9d248701aa62ab6fcbab
