### ISSUE TITLE
docs: change text to links in popup footer

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#219]
Change this readonly text to link: https://github.com/pingcap/tidb.ai

and change to text: "Powered by pingcap/tidb.ai, deploy your own for free."

<img width="837" alt="image" src="https://github.com/user-attachments/assets/0a3a24d6-e807-46f5-9854-1715dedab192">

**Comment by 634750802** [comment]
will be closed by https://github.com/pingcap/tidb.ai/commit/cf70efb3ce301cfdc1aad1f5eb20df77caef291f
