### ISSUE TITLE
error: This model's maximum context length is 8192 tokens

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#265]
Embedding Model: openai/text-embedding-3-small

openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens, however you requested 8610 tokens (8610 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.

**Comment by wd0517** [comment]
Update to the latest version (>= 0.2.6) should fix this error.
