### ISSUE TITLE
bug: frontend-1    | [proxy] PUT http://backend/api/v1/admin/site-settings/homepage_title 204 No Content application/json

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#283]
Can't update site settings e.g. titles, descriptions, example questions

**Comment by sykp241095** [comment]
<img width="945" alt="image" src="https://github.com/user-attachments/assets/40bd4866-f18a-44e1-a5c2-ed760a25b1db">

**Comment by wd0517** [comment]
I can't reproduce this bug, can you provide more details?

**Comment by sykp241095** [comment]
Provided by calling.

**Comment by wd0517** [comment]
Please update your image version to 0.2.7 or higher.
