### ISSUE TITLE
js-widget: users can perform a blank additional question after the first question

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#286]
![image](https://github.com/user-attachments/assets/c1463db4-46e0-4896-bcb0-143623fcc81f)

**Comment by sykp241095** [comment]
@wd0517 Isn't there a backend verfication logic ?

**Comment by wd0517** [comment]
https://github.com/pingcap/tidb.ai/commit/4503d0f714139b15bdd27fdcc56873f01d111523
