### ISSUE TITLE
feedback-ui: use obvious emoji on feedbak

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#288]
Use 
<img width="115" alt="image" src="https://github.com/user-attachments/assets/706950f8-1c53-43a1-a33d-64e10217435c">

instead of
<img width="90" alt="image" src="https://github.com/user-attachments/assets/8f4d7d61-4a90-4137-b589-a57e3698f535">

Use 
<img width="47" alt="image" src="https://github.com/user-attachments/assets/68cd6cae-2db8-4aa6-82bd-0633f47907e2">
instead of
<img width="44" alt="image" src="https://github.com/user-attachments/assets/38a219db-2451-4080-a8cb-a4bf4d902123">
which is more like a battery.

Use a up-style button
<img width="186" alt="image" src="https://github.com/user-attachments/assets/81e5c956-b778-4ff3-939d-88ce0b8c00e0">

instead of right-style
<img width="154" alt="image" src="https://github.com/user-attachments/assets/5a07b084-a6d3-4a98-9e19-924cda265e33">
to follow the most famous chatbot - ChatGPT.

**Comment by HiSeren** [comment]
Add some hover text could help understanding.
