### ISSUE TITLE
feature: enhanced docs search

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#320]
Currently we only support search by URL, it doesn't make sense: https://tidb.ai/documents

We should enable searching with name, tille, url or any reasonable fields. and also with enough filters like: `mime_type`

**Comment by Icemap** [comment]
Hi @sykp241095. Would you mind describing this feature more specifically? Now, we can only search the URL for sure. And in the database, we have some other fields, which are:

- `created_at`
- `updated_at`
- `name`
- `content`
- `mime_type`
- `last_modified_at`
- `meta`
- `index_status`

Which fields should we add to the enhanced doc search API?

**Comment by sykp241095** [comment]
@Icemap we can do it with best practice? you can ignore my suggestions. 

(I am not sure if mimetype is a ENUM or not)

**Comment by Icemap** [comment]
Yes. mime_type is an enum type. Aside from that, I added `created_at_start`, `created_at_end`, `updated_at_start`, `updated_at_end`, `last_modified_at_start`, `last_modified_at_end`, `name`, `mime_type`, `index_status`, `language`, and `product` filters. Also, change the blur name `query` to `source_uri`. @sykp241095 PTAL.

**Comment by Icemap** [comment]
Feature completed. If you have any questions, please feel free to reopen this issue.
